/// <reference lib="es2017" />

// MarkLogic built-in globals
/// <reference path="./globals.d.ts" />

// MarkLogic built-in objects
/// <reference path="./builtins/AccessPlan.d.ts" />
/// <reference path="./builtins/Attr.d.ts" />
/// <reference path="./builtins/CharacterData.d.ts" />
/// <reference path="./builtins/Comment.d.ts" />
/// <reference path="./builtins/Document.d.ts" />
/// <reference path="./builtins/DocumentsSearch.d.ts" />
/// <reference path="./builtins/Element.d.ts" />
/// <reference path="./builtins/FacetDefinition.d.ts" />
/// <reference path="./builtins/FacetsSearch.d.ts" />
/// <reference path="./builtins/IteratePlan.d.ts" />
/// <reference path="./builtins/ModifyPlan.d.ts" />
/// <reference path="./builtins/NamedNodeMap.d.ts" />
/// <reference path="./builtins/Node.d.ts" />
/// <reference path="./builtins/NodeBuilder.d.ts" />
/// <reference path="./builtins/NodeList.d.ts" />
/// <reference path="./builtins/Plan.d.ts" />
/// <reference path="./builtins/PreparePlan.d.ts" />
/// <reference path="./builtins/Sequence.d.ts" />
/// <reference path="./builtins/TuplesSearch.d.ts" />
/// <reference path="./builtins/TypeInfo.d.ts" />
/// <reference path="./builtins/Value.d.ts" />
/// <reference path="./builtins/ValuesSearch.d.ts" />
/// <reference path="./builtins/WordsSearch.d.ts" />
/// <reference path="./builtins/XMLDocument.d.ts" />
/// <reference path="./builtins/XMLNode.d.ts" />

// MarkLogic proprietary modules
/// <reference path="./modules/cdict.d.ts" />
/// <reference path="./modules/clang.d.ts" />
/// <reference path="./modules/cma.d.ts" />
/// <reference path="./modules/console.d.ts" />
/// <reference path="./modules/cpf.d.ts" />
/// <reference path="./modules/cts.d.ts" />
/// <reference path="./modules/dls.d.ts" />
/// <reference path="./modules/entity.d.ts" />
/// <reference path="./modules/es.d.ts" />
/// <reference path="./modules/flexrep.d.ts" />
/// <reference path="./modules/fn.d.ts" />
/// <reference path="./modules/geo.d.ts" />
/// <reference path="./modules/geogml.d.ts" />
/// <reference path="./modules/geojson.d.ts" />
/// <reference path="./modules/geokml.d.ts" />
/// <reference path="./modules/georss.d.ts" />
/// <reference path="./modules/jsearch.d.ts" />
/// <reference path="./modules/json.d.ts" />
/// <reference path="./modules/math.d.ts" />
/// <reference path="./modules/op.d.ts" />
/// <reference path="./modules/opdsl.d.ts" />
/// <reference path="./modules/ordt.d.ts" />
/// <reference path="./modules/prof.d.ts" />
/// <reference path="./modules/qbe.d.ts" />
/// <reference path="./modules/rdf.d.ts" />
/// <reference path="./modules/rdt.d.ts" />
/// <reference path="./modules/sec.d.ts" />
/// <reference path="./modules/sem.d.ts" />
/// <reference path="./modules/xdmp.d.ts" />
/// <reference path="./modules/xs.d.ts" />

// Make it all play nice
/// <reference path="./globals.global.d.ts" />
